module.exports = {
  DATABASE_CONNECTED: "Database connected.",
  DATABASE_CONNECTION_ERROR: "Failed to connect to database.",
  INTERNAL_SERVER_ERROR: "Internal server error.",
  ADMIN_LOGGED_IN: "Admin logged in.",
  INCORRECT_CREDENTIALS: "Incorrect credentials.",
  ADMIN_PROFILE_UPDATED: "Admin profile updated.",
  ADMIN_PROFILE_FETCHED: "Admin profile fetched.",
  FAILED_TO_UPDATE_PROFILE: "Failed to edit profile.",
  FAILED_TO_DELETE_ACCOUNT: "Failed to delete account.",
  TOKEN_NOT_AUTHORIZED: 'Token not authorized.',
  TOKEN_NOT_VALID: 'Token not valid.',
  CURRENT_PASSWORD_INCORRECT: 'Current password is incorrect.',
  PASSWORD_CHANGED: 'Password changed successfully.',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token.',
  NEW_ACCESS_TOKEN: 'New access token generated.',
};
